create database mydatabase;
use mydatabase;
select *from mytable limit 10;

-- Q1. what is the total revenue generated by male vs female patient ?
 select gender, SUM(purchase_amount) as revenue
 from mytable
 group by gender;
 
 -- Q2 which customer used a discount but still spent more than the average purchase amount
 select customer_id,purchase_amount

 from mytable
 where discount_applied= "Yes" and purchase_amount>= (select avg(purchase_amount) from mytable);
 
 -- Q3 which are the top 5 products with the highest average review rating
 
 select item_purchased, ROUND(avg(review_rating),2) as "Average Product rating"
 from mytable
 group by item_purchased
 order by avg(review_rating) desc
 limit 5;
 
 -- Q4.Compare the avaerage purchase amount between Standards and Express Shipping
select shipping_type,
round(avg(purchase_amount),2)
from mytable
where shipping_type in ('standard','Express')
group by shipping_type;

-- Q.5 Do Subscribed customer spend more? Compare average spend and total 
-- revenue between subscribers and non-subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from mytable
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q.6. Which 5 products have the highest percentage of purchases with discount appiled?
select * from mytable;
select item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100,2) as discount_rate 
from mytable
group by item_purchased
order by discount_rate desc 
limit 5;

-- Q7.Segment Customer intro new,Returning,and loyal based on their total 
-- number of previous purchases and show the count of each segment ?
with customer_type as (
select customer_id,previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10  THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment 
from mytable
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;



-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) DESC) as item_rank
from mytable
group by category,item_purchased
)

select item_Rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;
